# Import base image
FROM python:3.11-slim-buster

# Create a working directory
WORKDIR /app

# Install necessary packages for Ollama and curl
RUN apt-get update && \
    apt-get install -y curl && \
    apt-get clean

# Install Ollama
RUN curl -fsSL https://ollama.com/install.sh | sh

# Install Python dependencies
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

# Copy the application code
COPY . .

# Add a health check
HEALTHCHECK --interval=1200s --timeout=520s --start-period=120s --retries=1 \
CMD curl --fail http://localhost:8080/health || exit 1

# Start Ollama in the background and pull the model
#here change the model name you want to use ,due to system constraint llama3.2:1b is in use
CMD ["sh", "-c", "ollama serve & sleep 10 && ollama pull llama3.2:1b && uvicorn app:app --host 0.0.0.0 --port 8080"]

